version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@1.1.6

    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn install

      - run: yarn run test
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy Development"
              yarn run build
              ./node_modules/netlify-cli/bin/cli.js deploy \
                --site-id ${DEV_SITE_ID} \
                -p build/ \
                --access-token ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi
