version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i
            - run: npm test
            - run: npm run build
            - run: sudo npm install netlify-cli -g
            - run: netlify deploy -p -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}

workflows:
  build-test-deploy:
    jobs:
      - build-test-deploy:
          filters:
            branches:
              only: master
