version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn add netlify-cli
            - run: yarn test
            - run: yarn build
            - run: yarn netlify deploy --prod -d build ${NETLIFY_AUTH_TOKEN} ${NETLIFY_SITE_ID}
workflows:
  build-and-test:
    jobs:
      - build-and-test
          filters:
            branches:
              only:
                - master
