version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn add netlify-cli
            - run: yarn build
            - run: yarn netlify deploy --prod -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
