version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn add netlify-cli
            - run: yarn build
            - run: yarn netlify deploy -p -d build -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}

workflows:
  build-test-deploy:
    jobs:
      - build-test-deploy:
          filters:
            branches:
              only: master
