version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  yarn_install:
    steps:
      - restore_cache:
          name: Restore Dependencies
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Dependencies
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
  test:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run:
          name: Test Project
          command: yarn test
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - yarn_install
      - run:
          name: Deploy Project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy Development"
              yarn run build
              ./node_modules/netlify-cli/bin/cli.js deploy \
                --site-id ${DEV_SITE_ID} \
                -p build/ \
                --access-token ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
