version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn build
            - run:
                name: deploy
                command: |
                if [[ "$CIRCLE_BRANCH" = "master" ]]; then
                node_modules/netlify-cli/bin/cli.js deploy --site-id $DEV_SITE_ID -p build/ --access-token $NETLIFY_TOKEN
                fi
workflows:
  build-and-test:
    jobs:
      - build-and-test
        filters:
          branches:
            only:
              - master
