version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/openjdk:11-jdk-sid-node
    steps:
      - checkout
      - run:
          name: package install
          command: npm install
      - run:
          name: functions package install
          command: cd functions/ && npm install
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "functions/package.json" }}
      - run:
          name: firebase-tools install
          command: cd functions/ && npm install -D firebase-tools
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase --project default deploy --token=$FIREBASE_TOKEN